wandb: false
wdb_proj_name: shap_pc_testing
dump_args: true
overwrite_args: false
dump_results: true
overwrite_res: true
dump_data: false
overwrite_data: false
debug: false
start_iter: 0
output_dir: runs/ 
expt_name: sachs 
run_name: real_all                              
data_dir: datasets   
device: ''
compute_extra_metrics: false
main_seed: 2023
num_data_per_graph: 10
graph_type: 'real'
method: ['spc','pc_max','cam','fgs','nt','mcsl']
sem_type: ['sachs']
s: []
n_nodes: []
edge_per_node: []
w_ranges: ''
min_abs_unif: ''
max_abs_unif: ''
noise_scale_vec: false
test_alpha: [0.01]
test_name: ["kci"]
priority: 2
selection: ['bot'] 