wandb: false                               
wdb_proj_name: shap_pc_testing
dump_args: true
overwrite_args: false
dump_results: true
overwrite_res: false
dump_data: true
overwrite_data: false
debug: false
start_iter: 0
output_dir: runs/  
expt_name: ERSF124_d50_linear001
run_name: all_pc_linear             
data_dir: ../datasets/synthetic_data/    
device: ''                  
time_limit: 1200
compute_extra_metrics: true
main_seed: 2024
graph_type: ['ER','SF']
num_data_per_graph: 10
standardise: true
n_nodes: [10,20,50]
max_degree: 10
edge_per_node: [1,2,4]
pct_weak: 0.05
s: [100, 500, 1000]
w_ranges: ((-1.5, -0.5), (0.5, 1.5))
method: ['pc', 'spc', 'pc_max', 'pc_maj', 'pc_con']
sem_type: ['gauss', 'exp', 'gumbel', 'uniform']
test_alpha: [0.01]
test_name: ["fisherz"]
selection: ['neg']
priority: 3